### PR TITLE
Title as function and no autocapitalise

### PR DESCRIPTION
**Pull request by eugenisan**
Added options to run title as a function and noCaps parameter

### CODE REVIEW

**Comment by monbro** [comment]
awesome, I will test and merge this soon!

**Comment by eugenisan** [comment]
coolio! thanks :)

eugeni sánchez

**Comment by eugenisan** [comment]
nice! would it be too much if i asked you to update this on atmospherejs.com http://atmospherejs.com/ too?

thanks very much! :-)

eugeni sánchez

**Comment by monbro** [comment]
Haha not at all, I simply forgot, sorry! I just updated https://atmospherejs.com/monbro/iron-router-breadcrumb

**Comment by eugenisan** [comment]
brilliant! thanks a bunch… i can go back to the official version now… ;)

eugeni sánchez

**Pull request merged**
